Question 1

In [4]:
import numpy as np

In [5]:
arr1 = np.random.randint(1, 100, (5, 3))
print ("arr1: ")
print(arr1)

arr1: 
[[93 30  1]
 [13 37 24]
 [82 65 82]
 [95 84 89]
 [90 91 70]]


Question 2


In [6]:
n = arr1[2, 2]
print("Number in row 3, column 3 = ", n)

Number in row 3, column 3 =  82


Question 3

In [7]:
arr_slice = arr1[0:5:2]

In [8]:
#2 in the step segment means it only prints out every other array.
print(arr_slice)

[[93 30  1]
 [82 65 82]
 [90 91 70]]


Question 4



In [9]:
#Because arr1 is an array and not an asarray, this change will not be reflected. Putting [-1, -1] will insure 12345 goes to the end of the array.
arr_slice[-1, -1] = 12345

In [10]:
print(arr_slice)

[[   93    30     1]
 [   82    65    82]
 [   90    91 12345]]


Question 5

In [11]:
#Transposing
Transposed_array = arr1.transpose()

In [12]:
print(Transposed_array)

[[   93    13    82    95    90]
 [   30    37    65    84    91]
 [    1    24    82    89 12345]]


Question 6

In [13]:
#Creating a second array that uses odd numbers only between 0 to 40. Reshape makes 4 rows with 5 columns.
arr2 = np.arange(1, 41, 2)
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [14]:
print(arr2.reshape(4, 5))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


Question 7

In [15]:
#Making a new array by horizontally stacking the first two.
arr_new = np.hstack((arr1, arr2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [16]:
#However, we run into an error because they do not have the same size as each other. We must make sure arr2 has the same rows and columns as arr1.


In [17]:
new_arr2 = np.random.randint(1, 100, (5, 3))

In [18]:
print(new_arr2)

[[91 17 32]
 [74 20 38]
 [39 68 73]
 [97 60 53]
 [95 31 45]]


In [19]:
arr_new = np.hstack((arr1, new_arr2))

In [20]:
print(arr_new)

[[   93    30     1    91    17    32]
 [   13    37    24    74    20    38]
 [   82    65    82    39    68    73]
 [   95    84    89    97    60    53]
 [   90    91 12345    95    31    45]]


Question 8


In [23]:
arr1_summed = np.sum(arr1, axis = 0)

In [24]:
print(arr1_summed)

[  373   307 12541]


Question 9

In [152]:
#Matrix and Element Wise Multiplication 
arr3 = np.random.randint(1, 10, size=(3, 4))
arr4 = np.random.randint(1, 10, size=(5, 3))

In [153]:
MMarrayexample = np.dot(arr1, arr3)

In [154]:
EWMarrayexample = arr1 * arr4

In [157]:
print("\nMatrix Multiplication Example:")
print(MMarrayexample)

print("\nElement-wise Multiplication Example:")
print(EWMarrayexample)


Matrix Multiplication Example:
[[  510   308   273   584]
 [  895   706   461  1013]
 [  659   698   472   751]
 [  396   342   268   454]
 [74493 37415 49623 86894]]

Element-wise Multiplication Example:
[[   36   217   117]
 [  264   693    48]
 [   63   154    42]
 [  144    24    66]
 [  125    62 86415]]


Question 10

In [52]:
#Creating a 1D, 2D, and 3D array
arr_1d = np.arange(1, 4)

print("1D Array:", arr_1d)

arr_2d = np.array([np.arange(3) + 1, np.arange(3) + 1])

print("2D Array:")
print(arr_2d)

arr_3d = np.array([[[1, 2, 3]]] * 9)

print("3D Array:")
print(arr_3d)

1D Array: [1 2 3]
2D Array:
[[1 2 3]
 [1 2 3]]
3D Array:
[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


THIS IS AN INDIVIDUAL ASSIGNMENT. YOU MAY NOT DISCUSS THIS ASSIGNMENT WITH ANYONE WITHIN OR OUTSIDE THE CLASS (except the instructor).
- DO not discuss your approaches or your code with colleagues. There are many ways to implement this assignment, and it is extremely easy to spot code that has been inspired by someone else’s code and to identify unauthorized collaborations.
- If you choose to utilize something you find online, cite that resource, but DO NOT share that resource with anyone else.
By submitting this assignment, you certify that no unauthorized assistance has been received or given in the completion of this work.

In [200]:
#Kade Levy